[package]
name = "goldcrest"
version = "0.2.0"
authors = ["Tom Panton <pantonshire@gmail.com>"]
edition = "2018"

[dependencies]
tonic = "0.4"
prost = "0.7"
tokio = { version = "1.0", features = ["macros", "time"] }
chrono = "0.4"
bitvec = "0.20"

[build-dependencies]
tonic-build = "0.4"