[package]
name = "goldcrest"
version = "0.1.0"
authors = ["Thomas Panton <tom@tomandtally.co.uk>"]
edition = "2018"

[dependencies]
tonic = "0.3"
prost = "0.6"
tokio = { version = "0.2", features = ["macros", "time"] }
chrono = "0.4"
bitvec = "0.20"

[build-dependencies]
tonic-build = "0.3"