[package]
name = "goldcrest"
version = "0.3.0"
authors = ["Tom Panton <pantonshire@gmail.com>"]
edition = "2018"

[dependencies]
tonic = "0.4"
prost = "0.7"
tokio = { version = "1", features = ["macros", "time"] }
chrono = "0.4"

[build-dependencies]
tonic-build = "0.4"
